CREATE DATABASE SENAI_NOTES;
GO
USE SENAI_NOTES;
GO

CREATE TABLE NOTES_USER(
	IdUser INT PRIMARY KEY IDENTITY,
	Name VARCHAR(MAX),
	Email VARCHAR(MAX),
	Password VARCHAR(MAX),
	UserThemePreferences INT,
	UserFontPreferences INT,
	CreatedAt DATETIME
	
);
CREATE TABLE NOTE (
	IdNote INT PRIMARY KEY IDENTITY,
	Title VARCHAR(MAX),
	Content NVARCHAR(MAX),
	ImageUrl VARCHAR(MAX),
	IsFavorite BIT,
	IsArchived BIT,
	CreatedAt DATETIME,
	UpdatedAt DATETIME,
	IdUser INT FOREIGN KEY REFERENCES NOTES_USER(IdUser)	

);
CREATE TABLE TAG (
	IdTag INT PRIMARY KEY IDENTITY,
	Name VARCHAR(MAX)
);
CREATE TABLE NOTETAG (
	IdNoteTag INT PRIMARY KEY IDENTITY,
	IdNote INT FOREIGN KEY REFERENCES NOTE (IdNote),
	IdTag INT FOREIGN KEY REFERENCES TAG (IdTag)
);
GO